$engine: 3
$onesync: on
name: Legacy Core
author: ENT510
description: Recipe for Legacy Core, Framework Simple and Intuible for all!

tasks:

  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: master
    subpath: resources
    dest: ./resources/[cfx-default]
    
  - action: remove_path
    path: ./resources/[cfx-default]/[gameplay]/chat

  - action: download_github
    src: https://github.com/ENT510/legacy-core-recipe
    ref: main  
    dest: ./tmp/recipe

  - action: move_path
    src: ./tmp/recipe/server.cfg
    dest: ./server.cfg

  - action: connect_database

  - action: download_github
    src: https://github.com/Legacy-Scripts/LEGACYCORE
    ref: main
    dest: ./tmp/core

  - action: query_database
    file: ./tmp/core/[DB]/legacysq.sql

  - action: waste_time 
    seconds: 5

  - action: move_path
    src: ./tmp/core/[core]/LEGACYCORE
    dest: ./resources/[core]/LEGACYCORE

  - action: move_path
    src: ./tmp/core/[LegacyResource]
    dest: ./resources/[LegacyResource]

  - action: move_path
    src: ./tmp/core/[DB]/legacysq.sql
    dest: ./database/legacysq.sql

  - action: move_path
     src: ./tmp/recipe/lgf.png
    dest: ./lgf.png


    # - action: download_github
    # src: https://github.com/ENT510/LGF_Inventory
    # ref: main
    # dest: ./resources/[standalone]/LGF_Inventory

  - action: download_github
    src: https://github.com/Legacy-Scripts/LGF_Utility
    ref: main
    dest: ./resources/[LegacyResource]/LGF_Utility


    
  - action: download_github
    src: https://github.com/Bob74/bob74_ipl
    ref: master
    dest: ./resources/[standalone]/bob74_ipl

  - action: download_github
    src: https://github.com/AvarianKnight/pma-voice
    ref: main
    dest: ./resources/[standalone]/pma-voice

  - action: download_github
    src: https://github.com/Legacy-Scripts/-LegacyCore-fivem-appearance
    ref: main
    dest: ./tmp/fivem-appearance


  - action: move_path
    src: ./tmp/fivem-appearance
    dest: ./resources/[standalone]/fivem-appearance

  - action: download_file
    path: ./tmp/files/ox_lib.zip
    url: https://github.com/overextended/ox_lib/releases/latest/download/ox_lib.zip

  - action: unzip
    dest: ./resources/[ox]
    src: ./tmp/files/ox_lib.zip

  - action: download_file
    path: ./tmp/files/ox_target.zip
    url: https://github.com/overextended/ox_target/releases/latest/download/ox_target.zip

  - action: unzip
    dest: ./resources/[ox]
    src: ./tmp/files/ox_target.zip

  - action: download_file
    path: ./tmp/files/oxmysql.zip
    url: https://github.com/overextended/oxmysql/releases/latest/download/oxmysql.zip

  - action: unzip
    dest: ./resources/[ox]
    src: ./tmp/files/oxmysql.zip

  ## Cleanup
  - action: remove_path
    path: ./tmp
